M48
; DRILL file {KiCad 6.0.11+dfsg-1~bpo11+1} date Thu Apr 13 18:06:49 2023
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2023-04-13T18:06:49+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1~bpo11+1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X120100Y-76850
X123800Y-88650
T2
X114175Y-70341
X114175Y-110981
T0
M30
