M48
; DRILL file {KiCad 7.0.5.1-1-g8f565ef7f0-dirty-deb11} date Wed Jul  5 14:49:23 2023
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2023-07-05T14:49:23+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5.1-1-g8f565ef7f0-dirty-deb11
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X5925Y-6509
X9625Y-18309
T2
X0Y0
X0Y-40640
T0
M30
